version: "3.3"
services:
  hermes-db:
    build:
      context: ./db/  
    image: saulocn/hermes-pg
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '128M'
    ports:
      - 5432:5432
    environment:
        PGUSER: hermes
        POSTGRES_USER: hermes
        POSTGRES_PASSWORD: pass_hermes
        POSTGRES_DB: hermes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  hermes-mq:
    build:
      context: ./artemis/
    image: saulocn/hermes-mq
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.5'
          memory: '128M'
    ports:
      - 8161:8161
    environment:
        ARTEMIS_BROKER: hermes
        ARTEMIS_USER: hermes
        ARTEMIS_PASSWORD: pass_hermes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8161"]
      interval: 1m30s
      timeout: 5s
      retries: 5
  hermes-api:
    build:
      context: ./hermes-api/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: saulocn/hermes-api
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
        reservations:
          cpus: '1'
          memory: '512M'
    ports:
      - 8080:8080
    environment:
        JAVA_OPTIONS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dmp.config.profile=compose"
        DB_USERNAME: hermes
        DB_PASSWORD: pass_hermes
        DB_HOST: hermes-db
        DB_NAME: hermes
    restart: always
    depends_on:
        - hermes-db
        - hermes-mq
  mailer:
    build:
      context: ./hermes-mailer/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: saulocn/hermes-mailer
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1024M'
        reservations:
          cpus: '1'
          memory: '512M'
    environment:
        JAVA_OPTIONS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dmp.config.profile=compose"
        DB_USERNAME: hermes
        DB_PASSWORD: pass_hermes
        DB_HOST: hermes-db
        DB_NAME: hermes
        MQ_HOST: hermes-mq
        MQ_PORT: 5672
        MQ_USERNAME: hermes
        MQ_PASSWORD: pass_hermes
        MAIL_MOCK: "true"
        MAIL_FROM: somemail@outlook.com
        MAIL_USERNAME: somemail@outlook.com
        MAIL_PASSWORD: somepass
        MAIL_SMTP: 'smtp-mail.outlook.com'
        MAIL_PORT: '587'
        MAIL_TLS: 'REQUIRED'
        MAIL_SSL: 'false'
    restart: always
    depends_on:
        - hermes-db
        - hermes-mq

