###
POST http://localhost:8080/message



###
POST http://localhost:8080/message
Content-Type: application/json

{
    "title": "Teste 1",
    "text": "<p>Here is an image for you: <img src=\"https://picsum.photos/200/300?random=1\"><p>Regards</p>",
    "content-type": "test",
    "recipients": ["risoga3378@enamelme.com"]
}